authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),

    # Auth
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout_view, name="logout"),
]

cdc/urls.py
from django.urls import path
from . import views

app_name = 'cdc'

urlpatterns = [
    path('', views.dashboard, name='dashboard')
]

student_tracking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('cdc/', include('cdc.urls')),
    path('skills/', include('skills.urls')),
    path('activity/', include('activity.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    # Password reset
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password/password_reset.html"), name='password_reset'),
    path('password_reset/sent/', auth_views.PasswordResetDoneView.as_view(template_name="password/password_reset_sent.html"), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password/password_reset_complete.html"), name='password_reset_complete'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from student.models import Student, Semester
from teacher.models import Teacher



def index(request):
    return render(request, 'home.html')




def about(request):
    return render(request, 'about.html')




def contact(request):
    return render(request, 'contact.html')




def login_view(request):
    if request.user.is_authenticated:
        if hasattr(request.user, 'student'):
            return redirect('student:dashboard')
        elif hasattr(request.user, 'teacher'):
            return redirect('teacher:dashboard')
        else:
            return redirect('cdc:dashboard')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        role = request.POST.get('role')

        if role == 'student':
            user = authenticate(request, username=username, password=password)
            if user is not None:
                user_temp = get_object_or_404(User, username=username)
                user_student = Student.objects.filter(user=user_temp)
                if not user_student.exists():
                    return redirect('authentication:login')
                login(request, user)
                return redirect('student:dashboard')
            else:
                return redirect('authentication:login')
        elif role == 'professor':
            user = authenticate(request, username=username, password=password)
            if user is not None:
                user_temp = get_object_or_404(User, username=username)
                user_teacher = Teacher.objects.filter(user=user_temp)
                if not user_teacher.exists():
                    return redirect('authentication:login')
                login(request, user)
                return redirect('teacher:dashboard')
            else:
                return redirect('authentication:login')
        elif role == 'cdc':
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('cdc:dashboard')
            else:
                return redirect('authentication:login')

    return render(request, 'signin.html')





def signup(request):
    if request.user.is_authenticated:
        if hasattr(request.user, 'student'):
            return redirect('student:dashboard')
        elif hasattr(request.user, 'teacher'):
            return redirect('teacher:dashboard')
        else:
            return redirect('cdc:dashboard')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        role = request.POST.get('role')

        if role == 'student':
            user_temp = User.objects.filter(username=username)
            if user_temp.exists():
                return redirect('authentication:login')
            user = User.objects.create_user(username=username, password=password)
            student = Student.objects.create(user=user)
            for i in range(1,9):
                Semester.objects.create(user=student, semester=i)
            return redirect('authentication:index')
        elif role == 'professor':
            user_temp = User.objects.filter(username=username)
            if user_temp.exists():
                return redirect('authentication:login')
            user = User.objects.create_user(username=username, password=password)
            Teacher.objects.create(user=user)
            return redirect('authentication:index')
    return render(request, 'signin.html')




def logout_view(request):
    logout(request)
    return redirect('authentication:login')

authentication/templates/about.html
{% extends 'base.html' %}
{% load static %}






{% block title %}
  About
{% endblock title %}
  



{% block css_link %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style2.css' %}" />
{% endblock css_link %}






{% block style %}
<style>
  body {
    margin: 0;
    font-family: Georgia, 'Times New Roman', Times, serif;
    background: url("img4.jpg");
  }


  .topnav {
    overflow: hidden;
    background-color: rgb(134, 131, 161);
  }

  .topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }

  .topnav a:hover {
    background-color: #ddd;
    color: black;
  }

  #log {
    margin: 0px 10px;
    padding: 0px 10px;

  }

  #log a {
    float: right;
    background-color: #0b71d1;
    border-radius: 20px;
    margin-left: 10px;
  }

  .topnav a.active {
    background-color: #4CAF50;
    color: white;
  }
</style>
{% endblock style %}









{% block content %}
<div class="about-section">
  <h1>About Us Page</h1>
  <p>This system provides records of students and help to create environment to track students activities.</p>

</div>

<h2 style="text-align:center">Our Support</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <img src="/w3images/team1.jpg" alt="" style="width:100%">
      <div class="container">
        <h2>RAHUL</h2>

        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        <p>r@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="/w3images/team2.jpg" alt="" style="width:100%">
      <div class="container">
        <h2>Partha</h2>

        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        <p>p@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="/w3images/team3.jpg" alt="" style="width:100%">
      <div class="container">
        <h2>Sayan</h2>

        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        <p>S@example.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

authentication/templates/contact.html
{% extends 'base.html' %}
{% load static %}





{% block title %}
  Contact
{% endblock title %}
  




{% block css_link %}
<link rel="stylesheet" href="{% static 'style9.css' %}" />
{% endblock css_link %}
  






{% block style %}
<style>
  body {
    margin: 0;
    font-family: Georgia, 'Times New Roman', Times, serif;
    background: url("img4.jpg");
  }


  .topnav {
    overflow: hidden;
    background-color: rgb(134, 131, 161);
  }

  .topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }

  .topnav a:hover {
    background-color: #ddd;
    color: black;
  }

  #log {
    margin: 0px 10px;
    padding: 0px 10px;

  }

  #log a {
    float: right;
    background-color: #0b71d1;
    border-radius: 20px;
    margin-left: 10px;
  }

  .topnav a.active {
    background-color: #4CAF50;
    color: white;
  }
</style>
{% endblock style %}
  

    




{% block content %}
<div class="container">
  <span class="big-circle"></span>
  <img src="{% static 'img/shape.png' %}" class="square" alt="" />
  <div class="form">
    <div class="contact-info">
      <h3 class="title">Let's get in touch</h3>
      <p class="text">
        
      </p>

      <div class="info">
        <div class="information">
          <img src="{% static 'img/location.png' %}" class="icon" alt="" />
          <p>Balarampur, mouza Beralia, Baruipur, Kolkata - 700144</p>
        </div>
        <div class="information">
          <img src="{% static 'img/email.png' %}" class="icon" alt="" />
          <p>info@gmitkolkata.org</p>
        </div>
        <div class="information">
          <img src="{% static 'img/phone.png' %}" class="icon" alt="" />
          <p>(033) 2440-1082 / 81, (0)9007379853</p>
          
    
        </div>
      </div>

      <div class="social-media">
        <p>Connect with us :</p>
        <div class="social-icons">
          <a href="#">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="#">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="#">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="#">
            <i class="fab fa-linkedin-in"></i>
          </a>
        </div>
      </div>
    </div>

    <div class="contact-form">
      <span class="circle one"></span>
      <span class="circle two"></span>

      <form action="index.html" autocomplete="off">
        <h3 class="title">Contact us</h3>
        <div class="input-container">
          <input type="text" name="name" class="input" />
          <label for="">Username</label>
          <span>Username</span>
        </div>
        <div class="input-container">
          <input type="email" name="email" class="input" />
          <label for="">Email</label>
          <span>Email</span>
        </div>
        <div class="input-container">
          <input type="tel" name="phone" class="input" />
          <label for="">Phone</label>
          <span>Phone</span>
        </div>
        <div class="input-container textarea">
          <textarea name="message" class="input"></textarea>
          <label for="">Message</label>
          <span>Message</span>
        </div>
        <input type="submit" value="Send" class="btn" />
      </form>
    </div>
  </div>
</div>
{% endblock content %}
  
    




{% block js_link %}
<script
src="https://kit.fontawesome.com/64d58efce2.js"
crossorigin="anonymous"
></script>
<script src="{% static 'app.js' %}"></script>
{% endblock js_link %}
  

authentication/templates/home.html
{% extends 'base.html' %}
{% load static %}




{% block title %}
  Home
{% endblock title %}
  



{% block css_link %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% endblock css_link %}
  


{% block style %}
<style>
  body {
    background-color: aqua;
    margin: 0;
    font-family: Georgia, 'Times New Roman', Times, serif;
    
  }


  .topnav {
    overflow: hidden;
    background-color: rgb(134, 131, 161);
  }

  .topnav a {
    float: left;
    display: block;
    color: #ffffff;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }

  .topnav a:hover {
    background-color: rgb(255, 255, 255);
    color: black;
  }

  #log {
    margin: 0px 10px;
    padding: 0px 10px;

  }

  #log a {
    float: right;
    background-color: #0b71d1;
    border-radius: 20px;
    margin-left: 10px;
  }

  .topnav a.active {
    background-color: #4CAF50;
    color: rgb(255, 255, 255);
  }


  h1 {
    font-size: 50px;
    color: rgb(20, 92, 76);

  }

  .carousel-inner img {
    width: 80%;
    height: 70%;
  }
</style>
{% endblock style %}



{% block content %}

<div>
  <div style="padding-center:16px">
    <div align="center">
      <h2 style="color:rgb(37, 170, 19)">Student Tracking System</h2>

      <div id="demo" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ul class="carousel-indicators">
          <li data-target="#demo" data-slide-to="0" class="active"></li>
          <li data-target="#demo" data-slide-to="1"></li>
          <li data-target="#demo" data-slide-to="2"></li>
        </ul>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'img/clg1.jpg' %}" alt="Los Angeles" width="1100" height="500">
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/clg2.jpg' %}" alt="Chicago" width="1100" height="500">
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/clg3.jpeg' %}" alt="New York" width="1100" height="500">
          </div>
        </div>

        <div>
          <h1>WELCOME TO GMIT STUDENT TRACKING SYSTEM</h1>

        </div>
      </div>

      <footer class="ftco-footer ftco-section">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Brief</h2>
              <p>YourDictionary’s thesaurus is an easy-to-use online resource with a variety of different words. We’re
                not just a dictionary providing you definitions to show you the meaning of words, we will help you to
                enhance your writing by providing you with synonyms and related terms.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Menu</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Record</a></li>
                <li><a href="#" class="py-2 d-block">About</a></li>
                <li><a href="#" class="py-2 d-block">Home</a></li>
                <li><a href="#" class="py-2 d-block">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Help</h2>
              <div class="d-flex">
                <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                  <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
                  <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
                </ul>
                <ul class="list-unstyled">
                  <li><a href="#" class="py-2 d-block">FAQs</a></li>
                  <li><a href="#" class="py-2 d-block">Contact</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Have a Questions?</h2>
              <div class="block-23 mb-3">
                <ul>
                  <li><span class="icon icon-map-marker"></span><span class="text">Baruipur, Kolkata, West Bengal,
                      India</span></li>
                  <li><a href="#"><span class="icon icon-phone"></span><span class="text">+91 7781821986</span></a>
                  </li>
                  <li><a href="#"><span class="icon icon-envelope"></span><span
                        class="text">sayandey450@gmail.com</span></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;
              <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
              with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="#" target="_blank">SAYAN</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>
        </div>

      </footer>
    </div>
  </div>
</div>
{% endblock content %}
  



{% block js_link %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock js_link %}
  

authentication/templates/signin.html
{% extends 'base.html' %}
{% load static %}






{% block title %}
Signin
{% endblock title %}




{% block css_link %}
<link rel="stylesheet" href="{% static 'style13.css' %}" />
{% endblock css_link %}







{% block style %}
<style>
  body {
    margin: 0;
    font-family: Georgia, 'Times New Roman', Times, serif;
    background: url("img4.jpg");
  }


  .topnav {
    overflow: hidden;
    background-color: rgb(134, 131, 161);
  }

  .topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
  }

  .topnav a:hover {
    background-color: #ddd;
    color: black;
  }

  #log {
    margin: 0px 10px;
    padding: 0px 10px;

  }

  #log a {
    float: right;
    background-color: #0b71d1;
    border-radius: 20px;
    margin-left: 10px;
  }

  .topnav a.active {
    background-color: #4CAF50;
    color: white;
  }


  .register .nav-tabs {
    margin-top: 3%;
    border: none;
    background: #0062cc;
    border-radius: 1.5rem;
    width: 28%;
    float: right;
  }

  .register .nav-tabs .nav-link {
    padding: 2%;
    height: 34px;
    font-weight: 600;
    color: #fff;
    border-top-right-radius: 1.5rem;
    border-bottom-right-radius: 1.5rem;
  }

  .register .nav-tabs .nav-link:hover {
    border: none;
  }

  .register .nav-tabs .nav-link.active {
    width: 109px;
    color: #0062cc;
    border: 2px solid #0062cc;
    border-top-left-radius: 1.5rem;
    border-bottom-left-radius: 1.5rem;
  }

  .register-heading {
    text-align: center;
    margin-top: 8%;
    margin-bottom: -15%;
    color: #495057;
  }
</style>
{% endblock style %}







{% block content %}
<div class="container">
  <div class="forms-container">
    <div class="signin-signup">
      <form action="{% url 'authentication:login' %}" class="sign-in-form" method="POST">
        {% csrf_token %}
        <h2 class="title">Sign in</h2>

        <select name="role" id="" class="custom-select" required>

          <option value="student">STUDENT</option>
          <option value="professor">PROFESSOR</option>
          <option value="cdc">CDC</option>
        </select>


        <div class="input-field">
          <i class="fas fa-user"></i>
          <input type="text" name="username" placeholder="Username" />
        </div>
        <div class="input-field">
          <i class="fas fa-lock"></i>
          <input type="password" name="password" placeholder="Password" />
        </div>
        <a href="{% url 'password_reset' %}">Forgot password?</a>
        <input type="submit" value="Login" class="btn solid" />

      </form>
      <form action="{% url 'authentication:signup' %}" class="sign-up-form" method="POST">
        {% csrf_token %}
        <h2 class="title">Sign up</h2>
        <select name="role" class="custom-select" required>

          <option value="student">STUDENT</option>
          <option value="professor">PROFESSOR</option>

        </select>



        <div class="input-field">
          <i class="fas fa-envelope"></i>
          <input type="text" name="username" placeholder="Username" />
        </div>
        <div class="input-field">
          <i class="fas fa-lock"></i>
          <input type="password" name="password" placeholder="Password" />
        </div>
        <input type="submit" class="btn" value="Sign up" />

      </form>
    </div>
  </div>

  <div class="panels-container">
    <div class="panel left-panel">
      <div class="content">
        <h3>New here ?</h3>
        <p>
          Creat your New Account

        </p>
        <button class="btn transparent" id="sign-up-btn">
          Sign up
        </button>
      </div>
      <img src="{% static 'img/log.svg' %}" class="image" alt="" />
    </div>
    <div class="panel right-panel">
      <div class="content">
        <h3>One of us ?</h3>
        <p>
          Enter in your Profile if it is already exist

        </p>
        <button class="btn transparent" id="sign-in-btn">
          Sign in
        </button>
      </div>
      <img src="{% static 'img/register.svg' %}" class="image" alt="" />
    </div>
  </div>
</div>
{% endblock content %}





{% block js_link %}
<script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
<script src="{% static 'app2.js' %}"></script>
{% endblock js_link %}