authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),

    # Auth
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout_view, name="logout"),
]

cdc/urls.py
from django.urls import path
from . import views

app_name = 'cdc'

urlpatterns = [
    path('', views.dashboard, name='dashboard')
]

student_tracking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('cdc/', include('cdc.urls')),
    path('skills/', include('skills.urls')),
    path('activity/', include('activity.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    # Password reset
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password/password_reset.html"), name='password_reset'),
    path('password_reset/sent/', auth_views.PasswordResetDoneView.as_view(template_name="password/password_reset_sent.html"), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password/password_reset_complete.html"), name='password_reset_complete'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacher/urls.py
from django.urls import path
from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('update_profile/', views.update_profile, name="update_profile"),
    path('add_activity/', views.add_activity, name="add_activity"),
    path('all_students/', views.all_students, name="all_students"),
    path('add_marks/<id_student>/', views.add_marks, name="add_marks"),
    path('add_attendance/<id_student>/', views.add_attendance, name="add_attendance"),
]

teacher/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid





class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    id_teacher = models.CharField(max_length=255, blank=True)
    education = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    projects = models.TextField(blank=True)
    exp = models.TextField(blank=True)

    DEPT = (
        ('mechanical', 'Mechanical'),
        ('civil', 'Civil'),
        ('electrical', 'Electrical'),
        ('electronics', 'Electronics'),
        ('computer', 'Computer'),
        ('pharmacy', 'Pharmacy'),
    )
    department = models.CharField(max_length=50, choices=DEPT, blank=True, null=True)
    date_join = models.DateField(auto_now_add=True, null=True)
    img_profile = models.ImageField(upload_to="profile_img/", blank=True)

    def __str__(self):
        return self.user.username

    def get_all_student(self):
        return self.student_set.all() or None

    def get_url_image(self):
        return self.img_profile.url if self.img_profile else 'https://dummyimage.com/300.png/09f/fff'

    def get_name(self):
        return self.user.first_name if self.user.first_name else self.user.username

    def save(self, *args, **kwargs):
        if not self.id:
            self.id_teacher = str(uuid.uuid4())[:6]
        return super().save( *args, **kwargs)

    def get_display_skills(self):
        if self.user.skills_set.all().count() > 0:
            skills = ", ".join([x.skill for x in self.user.skills_set.all()])
        else:
            skills = "-"
        return skills

teacher/views.py
from django.shortcuts import render, redirect, get_object_or_404
from activity.models import Activity
from django.db.models import Q
import operator
from skills.models import Skills
from student.models import Student, Semester
from django.contrib.auth.decorators import login_required
from .decorator import is_teacher



@login_required(login_url='authentication:login')
@is_teacher
def dashboard(request):
    all_students = request.user.teacher.get_all_student()
    all_activites = []
    all_skills = Skills.objects.filter(user=request.user)

    activity = Activity.objects.filter(user=request.user)
    if activity.exists():
        for i in activity:
            if i not in all_activites:
                all_activites.append(i)

    if all_students:
        for student in all_students:
            act = Activity.objects.filter(user=student.user)
            if act.exists():
                for x in act:
                    if x not in all_activites:
                        all_activites.append(x)

    data = sorted(all_activites, key=operator.attrgetter('date'))    
    
    context = {
        'teacher': request.user.teacher,
        'activities': data[:20],
        'all_skills': all_skills,
    }
    return render(request, 'TeacherProfile.html', context)



@login_required(login_url='authentication:login')
@is_teacher
def update_profile(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        education = request.POST.get('education')
        location = request.POST.get('location')
        projects = request.POST.get('projects')
        exp = request.POST.get('exp')
        skills = request.POST.get('skills')
        department = request.POST.get('department')
        img_profile = request.FILES.get('img_profile')

        teacher = request.user.teacher

        teacher.user.first_name = name
        teacher.user.email = email
        teacher.education = education
        teacher.location = location
        teacher.projects = projects
        teacher.exp = exp
        Skills.objects.create(user=request.user, skill=skills)
        teacher.department = department

        if img_profile:
            teacher.img_profile = img_profile

        teacher.save()
        request.user.save()

        return redirect('teacher:dashboard')



@login_required(login_url='authentication:login')
@is_teacher
def add_activity(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        date = request.POST.get('date')
        activity = request.POST.get('activity')
        file = request.FILES.get('file')

        Activity.objects.create(user=request.user, name=name, date=date, activity=activity, file=file)

        return redirect('teacher:dashboard')



@login_required(login_url='authentication:login')
@is_teacher
def all_students(request):
    students = Student.objects.filter(teacher=request.user.teacher)

    mechanical = Student.objects.filter(department='mechanical').count()
    civil = Student.objects.filter(department='civil').count()
    electrical = Student.objects.filter(department='electrical').count()
    electronics = Student.objects.filter(department='electronics').count()
    computer = Student.objects.filter(department='computer').count()
    pharmacy = Student.objects.filter(department='pharmacy').count()

    context = {
        'students': students,
        'mechanical': mechanical,
        'civil': civil,
        'electrical': electrical,
        'electronics': electronics,
        'computer': computer,
        'pharmacy': pharmacy,
        'teacher': request.user.teacher
    }
    return render(request, 'students_profile.html', context)


@login_required(login_url='authentication:login')
@is_teacher
def add_marks(request, id_student):
    if request.method == 'POST':
        std = get_object_or_404(Student, id=id_student)
        for i in range(1,9):
            mark = request.POST.get('sem-' + str(i), None)
            if mark:
                semester = get_object_or_404(Semester, user=std, semester=i)
                semester.marks = mark
                semester.save()
    return redirect('teacher:all_students')



@login_required(login_url='authentication:login')
@is_teacher
def add_attendance(request, id_student):
    if request.method == 'POST':
        std = get_object_or_404(Student, id=id_student)
        for i in range(1,9):
            attendance = request.POST.get('sem-' + str(i), None)
            if attendance:
                semester = get_object_or_404(Semester, user=std, semester=i)
                semester.attendance = attendance
                semester.save()
    return redirect('teacher:all_students')

teacher/templates/students_profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{{ teacher.get_name }}</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition layout-top-nav">
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'authentication:logout' %}" class="nav-link text-danger">Logout</a>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->



    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Teacher Profile</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active"></li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Info boxes -->
          <div class="row">
            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box">
                <span class="info-box-icon bg-info elevation-1"><i class="fas fa-cog"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Mechanical</span>
                  <span class="info-box-number">
                    {{ mechanical }}
                  </span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>
            <!-- /.col -->
            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box mb-3">
                <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-hotel"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Civil</span>
                  <span class="info-box-number">{{ civil }}</span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>
            <!-- /.col -->

            <!-- fix for small devices only -->
            <div class="clearfix hidden-md-up"></div>

            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box mb-3">
                <span class="info-box-icon bg-success elevation-1"><i class="fas fa-bolt"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Electrical</span>
                  <span class="info-box-number">{{ electrical }}</span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>
            <!-- /.col -->
            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box mb-3">
                <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-wifi"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Electronics</span>
                  <span class="info-box-number">{{ electronics }}</span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>

            <div class="clearfix hidden-md-up"></div>

            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box mb-3">
                <span class="info-box-icon bg-success elevation-1"><i class="fas fa-laptop-code"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Computer</span>
                  <span class="info-box-number">{{ computer }}</span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>
            <!-- /.col -->
            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box mb-3">
                <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-flask"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Pharmacy</span>
                  <span class="info-box-number">{{ pharmacy }}</span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->

        </div>
        <!--/. container-fluid -->
      </section>
      <section class="content">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with default features</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>Image</th>
                      <th>Name</th>
                      <th>Reg No</th>
                      <th>Roll No</th>
                      <th>Semester</th>
                      <th>Year</th>
                      <th>Dept</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    
                    
                    {% for student in students %}
                    <tr>
                      <td><img alt="Avatar" class="table-avatar" src="{{ student.get_url_image }}" style="object-fit: cover; border-radius: 50%;" height="50" width="50"></td>
                      <td>{{ student.get_name }}</td>
                      <td>{{ student.reg_no }}</td>
                      <td>{{ student.roll_no }}th</td>
                      <td>{{ student.get_len_semester }}th</td>
                      <td>{{ student.year }}th</td>
                      <td>{{ student.get_department_display }}</td>
                      <td>
                        <a class="btn btn-primary btn-sm" data-toggle="modal" data-target="#marks-{{student.id}}" href="">
                          <i class="fas fa-list">
                          </i>
                          Marks
                        </a>
                        <a class="btn btn-success btn-sm" data-toggle="modal" data-target="#attendance-{{student.id}}" href="">
                          <i class="fas fa-check">
                          </i>
                          Attendance
                        </a>
                      </td>
                    </tr>

                    <!-- Modal -->
                    <div class="modal fade" id="marks-{{student.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Mark semesters</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <form class="form-horizontal" enctype="multipart/form-data" method="POST" action="{% url 'teacher:add_marks' student.id %}">
                              {% csrf_token %}
                              {% for sem in student.semester_set.all %}
                                <div class="mb-3">
                                  <input value="{{ sem.marks }}" max="10" min="0" type="number" class="form-control" name="sem-{{ sem.semester }}" placeholder="Semester {{ sem.semester }}">
                                </div>
                              {% endfor %}

                              
                              <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>

                    <!-- Modal -->
                    <div class="modal fade" id="attendance-{{student.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Attendance semesters</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <form class="form-horizontal" enctype="multipart/form-data" method="POST" action="{% url 'teacher:add_attendance' student.id %}">
                              {% csrf_token %}
                              {% for sem in student.semester_set.all %}
                                <div class="mb-3">
                                  <input value="{{ sem.attendance }}" max="10" min="0" type="number" class="form-control" name="sem-{{ sem.semester }}" placeholder="Semester {{ sem.semester }}">
                                </div>
                              {% endfor %}

                              
                              <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                      
                  </tbody>

                </table>
              </div>
              <!-- /.card-body -->
            </div>
          </div>
        </div>
      </section>

    </div>
    <!-- /.content-wrapper -->



    <!-- Main Footer -->
    <footer class="main-footer">
      <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
      All rights reserved.
      <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.0.2
      </div>
    </footer>
  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <!-- jQuery -->
  <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
  <!-- Bootstrap -->
  <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- overlayScrollbars -->
  <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'dist/js/adminlte.js' %}"></script>

  <!-- OPTIONAL SCRIPTS -->
  <script src="{% static 'dist/js/demo.js' %}"></script>

  <!-- PAGE PLUGINS -->
  <!-- jQuery Mapael -->
  <script src="{% static 'plugins/jquery-mousewheel/jquery.mousewheel.js' %}"></script>
  <script src="{% static 'plugins/raphael/raphael.min.js' %}"></script>
  <script src="{% static 'plugins/jquery-mapael/jquery.mapael.min.js' %}"></script>
  <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
  <!-- ChartJS -->
  <script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>

  <!-- PAGE SCRIPTS -->
  <script src="{% static 'dist/js/pages/dashboard2.js' %}"></script>
  <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{% static 'dist/js/demo.js' %}"></script>
  <script>
    $(function () {
      $("#example1").DataTable();
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
      });
    });
  </script>
</body>

</html>