authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),

    # Auth
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout_view, name="logout"),
]

cdc/urls.py
from django.urls import path
from . import views

app_name = 'cdc'

urlpatterns = [
    path('', views.dashboard, name='dashboard')
]

student_tracking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('cdc/', include('cdc.urls')),
    path('skills/', include('skills.urls')),
    path('activity/', include('activity.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    # Password reset
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password/password_reset.html"), name='password_reset'),
    path('password_reset/sent/', auth_views.PasswordResetDoneView.as_view(template_name="password/password_reset_sent.html"), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password/password_reset_complete.html"), name='password_reset_complete'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/password/password_reset.html
{% load add_class %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

	<title>Reset Password</title>
</head>
<body>
	
	<section class="pt-5">
		<div class="container">
			<div class="row">
				<div class="col-md-6 mx-auto">
					<form action="" class="border rounded p-3" method="POST">
						<h1>Reset Password</h1>
						<p class="mb-4">Enter your email address to send link for reset your password.</p>
						{% csrf_token %}
						{% for i in form %}
						<div class="mb-3">
							{{ i.label }}
							{{ i | addclass:'form-control' }}
						</div>
						{% endfor %}
						<button type="submit" class="btn btn-primary">Send email</button>
					</form>
				</div>
			</div>
		</div>
	</section>


	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

templates/password/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

	<title>Reset Password</title>
</head>
<body>
	<section class="pt-5">
		<div class="container">
			<div class="row">
				<div class="col-md-6 mx-auto">
					<div class="border rounded p-3">
						<h1>Your password have been changed!</h1>
						<p>Try to <a href="{% url 'authentication:login' %}">login</a> now.</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

templates/password/password_reset_confirm.html
{% load add_class %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

	<title>Reset Password</title>
</head>
<body>
	<section class="pt-5">
		<div class="container">
			<div class="row">
				<div class="col-md-6 mx-auto">
					<form action="" class="border rounded p-3" method="POST">
						<h1>Change Password</h1>
						<p class="mb-4">Enter new password.</p>
						{% csrf_token %}
						{% for i in form %}
						<div class="mb-3">
							{{ i.label }}
							{{ i | addclass:'form-control' }}
						</div>
						{% endfor %}
						<button type="submit" class="btn btn-primary">Submit</button>
					</form>
				</div>
			</div>
		</div>
	</section>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

templates/password/password_reset_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

	<title>Reset Password</title>
</head>
<body>
	<section class="pt-5">
		<div class="container">
			<div class="row">
				<div class="col-md-6 mx-auto">
					<div class="border rounded p-3">
						<h1>Email was sent!</h1>
						<p>Check your email inbox to reset passwrod. <a href="{% url 'authentication:login' %}">Login</a></p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>