activity/urls.py
from django.urls import path
from . import views

app_name = 'activity'

urlpatterns = [
    path('delete/<id_activity>/', views.delete_activity, name='delete_activity')
]

authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),

    # Auth
    path('login/', views.login_view, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout_view, name="logout"),
]

cdc/urls.py
from django.urls import path
from . import views

app_name = 'cdc'

urlpatterns = [
    path('', views.dashboard, name='dashboard')
]

student_tracking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('cdc/', include('cdc.urls')),
    path('skills/', include('skills.urls')),
    path('activity/', include('activity.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    # Password reset
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="password/password_reset.html"), name='password_reset'),
    path('password_reset/sent/', auth_views.PasswordResetDoneView.as_view(template_name="password/password_reset_sent.html"), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password/password_reset_complete.html"), name='password_reset_complete'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cdc/models.py
from django.db import models

# Create your models here.

student/models.py
from django.db import models
from django.contrib.auth.models import User
from teacher.models import Teacher


class Student(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    year = models.IntegerField(blank=True, null=True)
    reg_no = models.BigIntegerField(blank=True, null=True)
    roll_no = models.BigIntegerField(blank=True, null=True)
    education = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    projects = models.TextField(blank=True)
    exp = models.TextField(blank=True)
    DEPT = (
        ('mechanical', 'Mechanical'),
        ('civil', 'Civil'),
        ('electrical', 'Electrical'),
        ('electronics', 'Electronics'),
        ('computer', 'Computer'),
        ('pharmacy', 'Pharmacy'),
    )
    department = models.CharField(max_length=50, choices=DEPT, blank=True, null=True)
    img_profile = models.ImageField(upload_to="profile_img/", blank=True)

    def __str__(self):
        return self.user.username

    def get_name(self):
        return self.user.first_name if self.user.first_name else self.user.username
    
    def get_len_semester(self):
        return self.semester_set.all().count()

    def get_url_image(self):
        return self.img_profile.url if self.img_profile else 'https://dummyimage.com/300.png/09f/fff'

    def get_display_skills(self):
        if self.user.skills_set.all().count() > 0:
            skills = ", ".join([x.skill for x in self.user.skills_set.all()])
        else:
            skills = "-"
        return skills

    def is_activity(self):
        return self.user.activity_set.all().count() != 0





class Semester(models.Model):
    user = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    semester = models.IntegerField()
    marks = models.FloatField(blank=True, null=True)
    attendance = models.FloatField(blank=True, null=True)

    def __str__(self):
        return str(self.user) + ' | ' + str(self.semester)

    def get_marks(self):
        return self.marks / 100 * 1000

    def get_attendance(self):
        return self.attendance / 100 * 1000

cdc/views.py
from django.shortcuts import render
from student.models import Student

from django.contrib.auth.decorators import login_required
from .decorator import is_cdc


@login_required(login_url='authentication:login')
@is_cdc
def dashboard(request):
    students = Student.objects.all()

    mechanical = Student.objects.filter(department='mechanical').count()
    civil = Student.objects.filter(department='civil').count()
    electrical = Student.objects.filter(department='electrical').count()
    electronics = Student.objects.filter(department='electronics').count()
    computer = Student.objects.filter(department='computer').count()
    pharmacy = Student.objects.filter(department='pharmacy').count()

    context = {
        'students': students,
        'mechanical': mechanical,
        'civil': civil,
        'electrical': electrical,
        'electronics': electronics,
        'computer': computer,
        'pharmacy': pharmacy,
    }
    return render(request, 'cdc_profile.html', context)

cdc/templates/cdc_profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>GMIT Student Tracking System  | CDC Profile</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition layout-top-nav">
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'authentication:logout' %}" class="nav-link text-danger">Logout</a>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->



    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">CDC Profile</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active"></li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Info boxes -->
          <div class="row">
            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box">
                <span class="info-box-icon bg-info elevation-1"><i class="fas fa-cog"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Mechanical</span>
                  <span class="info-box-number">
                    {{ mechanical }}
                  </span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>
            <!-- /.col -->
            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box mb-3">
                <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-hotel"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Civil</span>
                  <span class="info-box-number">{{ civil }}</span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>
            <!-- /.col -->

            <!-- fix for small devices only -->
            <div class="clearfix hidden-md-up"></div>

            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box mb-3">
                <span class="info-box-icon bg-success elevation-1"><i class="fas fa-bolt"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Electrical</span>
                  <span class="info-box-number">{{ electrical }}</span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>
            <!-- /.col -->
            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box mb-3">
                <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-wifi"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Electronics</span>
                  <span class="info-box-number">{{ electronics }}</span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>

            <div class="clearfix hidden-md-up"></div>

            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box mb-3">
                <span class="info-box-icon bg-success elevation-1"><i class="fas fa-laptop-code"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Computer</span>
                  <span class="info-box-number">{{ computer }}</span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>
            <!-- /.col -->
            <div class="col-12 col-sm-6 col-md-2">
              <div class="info-box mb-3">
                <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-flask"></i></span>

                <div class="info-box-content">
                  <span class="info-box-text">Pharmacy</span>
                  <span class="info-box-number">{{ pharmacy }}</span>
                </div>
                <!-- /.info-box-content -->
              </div>
              <!-- /.info-box -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->

        </div>
        <!--/. container-fluid -->
      </section>
      <section class="content">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">DataTable with default features</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Id</th>
                      <th>Image</th>
                      <th>Semester</th>
                      <th>Year</th>
                      <th>Dept</th>
                      <th>Start Date</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    
                    
                    {% for student in students %}
                    {% if student.user.activity_set.all.count > 0 %}
                    <tr>
                      <td>{{ student.get_name }}</td>
                      <td>{{ student.teacher.id_teacher }}</td>
                      <td><img alt="Avatar" class="table-avatar" src="{{ student.get_url_image }}" style="object-fit: cover; border-radius: 50%;" height="50" width="50"></td>
                      <td>{{ student.get_len_semester }}th</td>
                      <td>{{ student.year }}th</td>
                      <td>{{ student.get_department_display }}</td>
                      <td>{{ student.teacher.date_join | date:'d/m/Y' }}</td>
                      <td class="project-actions text-right">
                        <a class="btn btn-primary btn-sm" target="_blank" href="{{ student.user.activity_set.all.0.file.url }}">
                          <i class="fas fa-folder">
                          </i>
                          View
                        </a>
                        <a class="btn btn-danger btn-sm" href="{% url 'activity:delete_activity' student.user.activity_set.all.0.id %}">
                          <i class="fas fa-trash">
                          </i>
                          Delete
                        </a>
                      </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                      
                  </tbody>

                </table>
              </div>
              <!-- /.card-body -->
            </div>
          </div>
        </div>
      </section>

    </div>
    <!-- /.content-wrapper -->



    <!-- Main Footer -->
    <footer class="main-footer">
      <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
      All rights reserved.
      <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.0.2
      </div>
    </footer>
  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <!-- jQuery -->
  <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
  <!-- Bootstrap -->
  <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <!-- overlayScrollbars -->
  <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'dist/js/adminlte.js' %}"></script>

  <!-- OPTIONAL SCRIPTS -->
  <script src="{% static 'dist/js/demo.js' %}"></script>

  <!-- PAGE PLUGINS -->
  <!-- jQuery Mapael -->
  <script src="{% static 'plugins/jquery-mousewheel/jquery.mousewheel.js' %}"></script>
  <script src="{% static 'plugins/raphael/raphael.min.js' %}"></script>
  <script src="{% static 'plugins/jquery-mapael/jquery.mapael.min.js' %}"></script>
  <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
  <!-- ChartJS -->
  <script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>

  <!-- PAGE SCRIPTS -->
  <script src="{% static 'dist/js/pages/dashboard2.js' %}"></script>
  <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{% static 'dist/js/demo.js' %}"></script>
  <script>
    $(function () {
      $("#example1").DataTable();
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
      });
    });
  </script>
</body>

</html>